

const hymnsData = {

"1. UNYIBWIRE EBIA YESU": "1. Unyibwire ebia Yesui, sakabiokomutima, Bianganyibohola kundu, okuebibibinene.\n\nUnyibwire ebia Yesui, sakabiokomutima, Bianganyibohoa kundu, okuebibi binene.\n\n2. Tuangabwirabandumwatsi, owasihirekundu, Ngokotuangabanangebe, Omuesi Wa YeKristo.",
"2. ERIA KOKALVARI YESU MOATUHALO": "1. Eriakokalvari, mohabyaomuti, musalabaWesisoni, Okomutioyoomubuyamoakwa.\n\nBosanana bandubabi.\nBosana neritulamya.\nBunguluyoweneyiwe.\nNgandipipaYesuMulamia, Oyowarihreebibi, moambaengebeyerikota, nage namuanzirekwenenene.\nNgandipipaIyeYesumubuya, eyaYesuKristo.\n\n2. Okomutioyo, mobagalyaYesu, nesiotutusiomobiala, neritumoeriomoriamutsimita.\n\n3. Ingyenakwamire, Yesuwakalvari, Omuamiawekihugo, nikwangandilinda, inynemotula.",
"3. YESU MOATUGENYERA KUNDU": "1. Yesumoatugenyerakundu, moakwaahotuangakwirire, riakokitwakiakalvari.\n\nMoatuholerakomuti.\nIniaturihira 'lubanza\nErinyihira eWaYesu.\nHaleluya, abiritulusiakoebibi,\nHaleluya, Haleluya, haleluya,\nHaleluya, haleluya Obuengebuwebulabire.\n\n2. Ebibibietunibinene, ebialekainiasyahola, buengebuwebualekire.\n\n3. Obuengebuwebuasyatuma, inalolakobusubuwe, musasiWuwemutika.",
"4. MUSONDOLI WA BAKRISTO": "1. YesuMusondoiwabakristo, Yesumuanzewelubula, AbirasihalingaYesu, Owendataalabire.\n\nHaleluya kaniYesu, Haleluya, werikota,\nAkanyilamaya, erinyibika, nanaka erihika okonduli.\n\n2. Yesuurimakawabakristo, Yesuukatukindira, Moatokaerilengwako kera, eritutokisyanetu.\n\n3. YesunabueneMungumubuya, Yesuakasibikaya, Enondimugenikutsenzama, eriaYesuandindire.",
"5. TUIMBE OLUIMBO LUOMUATSI": "1. TuimbeoluimboluamuatsiwaYesuOmulamia, OyowakwaOkomuti, nerilamiakihugo.\n\nEga, tupipeMuamiWetu,\nOyowatuhangebe,\nIyemoatu kolakibuya,\nAbirituwanituwania.\n\n2. Omulamiyayesukristo moaluaomobutuku, Moalolaokobuligre, nerituhabutseme.\n\n3. Nabyamunduweritala monzirayamalolo, Yesumoanyibirikira, moanyilusyakwebibi.",
"6. TUPIPE MUNGU NI MUENGE": "1. TupipeMungunimuenge, tumupipebanduboMumupipeabalaiika, Ise, Muana nEkirimu.\n\n2. Akarioakotukarya, Munguabirituhako Abirituhaengebe, uasingyakomulamia.",
"7. MUNGU NI MUENGE": "1. Munguninnenge, kamuatumayesuneritulamiali nomonziranyibi.\n\nAleluya tumukwame, Aleluya kundu, Aleluya YesuKristo, utuwanaye.\n\n2. TuyireYesu, Muinenengmuami, kosangwaabirihola neritulamia.\n\n3. Utusulaye, noluanzololuwawe, nobutsemebunenebwebirobiosi.\n\n4. Tulekebindubiekihugokino, tukwameYesuKristo, MukamaWetu.",
"8. YESU MOAHOLA KOMUTI":"HORATIUS BONAR/Arr. JAMES MC GRANAHAN\n\n1. Yesu mwahola komuti, aleluya, aleluya, e rikindaeSatana, aleluya, aleluya, erihưngarie lifere nekiniga kie kihugo, inobitetamukindaho, mupipe oMukama.\n\nHa leluya, haleluya, tupipe o' Mukama Yesu,\nHaleluya, haleluya, mwalihire ebibi.\n\n2. Okomusalaba oyo, aleluya, aleluya, Ye. su mwatuha omuinda,\naleluya, aleluya, eriganyira rio Mungu riasa busana na Yesu,\nOyo Waliha ebibi, tupipe oMukama.\n\n3. Wasingya tukaha Yesu, aleluya, aleluya, Omulamia no'Mukama,\naleluya, aleluya, ka moatukola kibuya,\nmoakwa ho tuangakwirire, akandisyaya akandi, tupipe oMukama.",
"9. NOYO ANZIRE ASE": "1. YesumoatuanZaisitumwasi, moakwaokomuti neritulamya, moaheka ebibibabandubosi.\n\nEkionikiawasingya Oyooanzire, Ase.\nNaweuangingiramo.\nNoyoanzire, asekuYesu,\nAsyabanangebeyoyerikota, oyoanawira, amakwanyota, angahikakuYesu.\n\n2. BirikiraobanduokoYesu, balekeenzira yerisyahera, bahikekuYesu, niMulamia.\n\n3. Neriositulindebalikietu, luyiluelubula lukingukere, Yesuninzir'eyo, tuangakwamire.",
"10. INGYE NYANZIRE ENGULU": "1. Ingyenyanzireengulu, yoyaYesuMukama, eritula omuatsiwoyowahola komuti, woyowalwamoisinda.\n\nIngyenangatulayo, kobihandabiosi, oluanzoluaYesuKristo, Muamioyowetu.\n\n2. Ingyenyanziremubiri, waYesuwakalvari, kosangwa moanyilusyakelubanza luerihera, neririharibibibi.\n\n3. Ingyenyanzireritula, omuatsiwomusasi, nesiotu tumobiala, neritumomolukanga, mobyagaliaMukama.\n\n4. Ingyenyanzirekitabu, ekiomukamaKristo, kikatubwiromuatsi, woyobuholo ewomungu, kikatubwiromuasi.",
"11. INGIE NALAMIRE MOMUSASI": "1. IngienalamiremoImuSasi, WoyowanyiholeraOkomuti, birinyibikaIno luanzoluWe, nabiribanangebeyiWe.\n\nNindi? niYesu akabugira ebibi,\nKaniYesu, kaniYesu,\nNiki? nimusasiwoyowaholakomuti.\nNimusasi, nimusasi.\n\n2. Keratuabyabanabekihugo, tuagendatukakolla bibibiakio, YesuKristomualihi ndihiyetu, moatuholerakoKalvari.\n\n3. Linotuangabwirabandumuatsi, koYesumoaholerahokomuti, tuabyangabokera Yesu moatuanZa, nabobangaminyaluanzoluwe.",
"12. KERA KERA MONAKOLA": "1. Kerakeramonakola ebibibialibimu, NikwalinoYesuKristo amanyilamiakundu.\n\nOmutimaOwage amanza, OkoebinywabiaYesu, mukamaOwenenga, kayomuiramubuya.\n\n2. YesuKristokamoanasabosa nerilamia, Eriheraeriabandu nerihabobutseme.\n\n3. YesuKristokamoholabosana nerieria, Mitimayabandubabi nerilusyaebibi.",
"13. MUNGU NI KAGALA KETU": "1. Mungunikagalaketu, wasingyakuYesu, SiendisyasigabuWenakera nakera.\n\n2. Hakuhinomunguwetus, siharibobuba, Satanaabirikindwatutsemirekundu.\n\n3. YehovamukamaWetu, weriko MgabyimbaDirobiosi nakagalakuwe.",
"14. SULIWAHIKA KU YESU MULAMIA": "1. SuliwahikakuYesuMulamia? Suliwahaniamomusasi? Uabirikiriyaerinariwe? OmutiawaWe erire?\n\nMutima (Mutima) erire (erire), Erire momusasiWuwe? (waYesu?) Uabirikiriya kuYesuKristo? Werire momusasiWuwe?\n\n2. Unemusabanomuhwamunene? OmutimaWewerire? UamutulaenguluyoWene? NomutimawaWe erire?\n\n3. UnemulindaOmukamaYesu? Nomutimayoyerire? Uabirilekaenzirayebibi? OmutimawaWe erire?",
"15. BIANGABYA NGE NZURURU":"FANNY J. CROSBY/WH DOANE\n\n1. Ebibi ebikinire biangabya ngomusohe;  sohe.\nOmuhinda nia webibi, angabya mue si.\n\nEbi bi ebikinire ebibi ebikinire,\nBiangabya nge nzururu, biangabya ngenzururu.\n\n2. Tasuba lino ko Mungu hulikirira tahi, tahi,\nOmulenge Owa Yesu, uamowa ta hi.\n\n3.  Angabugira ebibi ibiakuhwako biosi; biosi,\nTasa ma1i ra ko Yesu, embiroihwe.",
"16. OMUTIMA WAGE AMABINDUKIRA": "1. Omutima wage amabindukira Omukama wetu Yesu ekiakakala kiwe kiabirihika\nNabirileka erikwama Satana ekiro Yesu\nSu moingira abirie ria bibibia ge ebiosi\n\nBkiro Yesu muingira\nBkiro Yesu muingira\nWasingya ko Yesu Kristo\n\nEkiro Yesu muingira muno momutima wage\nObutsene bungi mobuahika kundu ekiro Yesu muingira\nYesu moingira Yesu moingira muno momutima waghe\n\n2. Nabirileka erikwama Satana ekiro Yesu\nSu moingira abirie ria bibibia ge ebiosi\n\n3. Monayiketera omukama Kristo ekiro Yesu\nSu moingira atokire emiatsi eyosiyage",
"17. MOANGABUTWA 'KANDI": "1. Nikodemo moasa ko Yesui kera eribulya enzira\nMuerilama Nerio Omukama moamusubiria\nMuangabutwa akandi.\n\nMuangabutwa akandi, muangabutwa akandi,\nKwene ne Yesu atinga kubwira, muangabutwa kandi.\n\n 2. Omunju amanza erilamibwa kwebibi nobuli\nGebunene Angaha Yesu Mutima Wuwe\nIniabutwa kandi.\n3. Omundu amakulinda endata oko muyi ahate\nOluholo Uamasonda eri Swamulolako\nIuabutwa kandi kandi.",
"18. YESU AKALAMAYA": "1. Yesu anzire bobatere Omobibi\nAkababirikira neribala engebe\n\nMuangimbalo ka muangimbao esiongendo nyingi Yesu Kristo\nAkalamaya uangabwira bo\nKristo O Mulamia Yesu akalamaya\nUangabwira bo, akandi ndeke, Yesu kalamaya.\n\n2. Iakandikuha engebe yerikota\nMundu webibi\n\n3. Lino\nAngakukokya lino uwe\nAbirieria biosi nebitingu biebibi",
"19. SINDI MOMULIKI WESATANA": "1. Sindi momuliki weSatana Nabirilama ku Yesu Kristo. Abirinyitongolia kwenenene.\n\nMoakinda Satana n'esionzigu siosi\nYesu akandikubohola kwenenene\nNa bere Omundu owa Yesu Kristo.\n\n2. Uase lino muntu webibi Ukandibana ebugira, Uiwe momuliki WeSatan,\n\n3. Omusasi Womukama Kristo Abiririha lubanza Twetu, Ingyesindi moMuiki lino,\n\nMoatoka kundu, uasingia. Abirisaka erina riage, Omokitabu ekio kiengebe, Yesu Kristo Mukama uri mubuya.",
"20. EKIBANZA KIEKANISA": "1. Kiban za kiekani sa ni Mukama Yesu\nNaye abumbireyo nakagala kuwe\nAsa neritu Sonda, tubye abana buwe\nKosangwa moatugula nomusasi Wuwe.\n\n2. Tukaliwa ko bihanda biosi biekihugo\nNikwa turi mugoma oko Muami Kristo\nEkanisa ya Yesu sihari eyindi\nNerina rigo maniria Yesu Kristo.\n\n3. Omokihugo kino muri enitab u\nEkanisa yosi yangakwama Kristo\nMonzira yobulige siendisya tusiga\nAkatuha buholo obo buerikota.",
"21. ERIKIRIRIA": "1. Erikiriria eriabakristo, riangabya nakagalakosi, Situangatoga monzira yiwe, kosangwa Muami arinetu.\n\nYesu Kristo, tukuanzire, niwe tukuamire, kundu.\nYesu Kristo, tukuanzire, niwe tukaumire, kundu.\nYesu Kristo, tukuanzire, niwe tukaumire, kundu.\nYesu Kristo, tukuanzire, niwe tukaumikundu.\n\n2. Banabibalolakobulige, bosananerina riaYesu, Netutukwamirenzira yabo, situendileka Mulamia\n\n3. Mobendererya Mulamia wetu, mobamuita komusalaba, Netutuasyasagamundu wahi, Yesu amabyaarinetu.\n\n4. Bkindikiro akandisyasa, netuituagendaewuWe, Linotukole mubiri wuwe, ngabakalinda Muami wabo.",
"22. ERINA RIA YESU RIBUYA": "1. ErinariaYesuribuya,rikasihaomomatwi, Rikaleetangebelenonerihigaeriubaha.\n\n2. YesuKristouiengebenenzirabusananetu, UriOmukamanomuami, tuamakusimakwenene.\n\n3. Siharierindierinamonakihugoeyikwa, Rikalekaitwamusaba, iyeMugalawomungu.\n\n4. YesuMunguaatuholera, rilusiaolubanza, Naweukakolakilino, noyowarihabingaha.",
"23. AKALEMBERA OMUTIMA WAGE": "FANNY JJ CROSBY/WM. J. KIRKPATRICK\n\n1. YesuniMulamiawagemubuyanabirimu Simakundu; Abirinyipingyanabirilama Mukamaamatoka\n\nAkalemberaomutimawage,\nOkuitebiariekihugo, akalemberaengebeyoyage,\nOmoluanzololuwe, sinangubahaekindu.\n\n2. Omulamiawagenimuengekundu, moaheka Bibibiage, Akambakagalanoluanzoluwe, bi Labireekihugo.\n\n3. Ekironasyangirirwaendata, nekanisa Eyoyiwe, Amaligewageasyahinduka, mo ButsemeobuaYesu.",
"24. UBWIRE YESU": "J. E. RANKIN/E.S. LORENZ\n\n1. Ukaluhauweswebibi, ubwiriyeYesu, ubwiriyeYesu, obiligemakuhikako, ubwiriyeYesubiosi.\n\nUbwiriyeYesu, ubwiriyeYesu,\nIyenimuirakundu, siwendisya-\nbanagundingaye, ubwiriyeYesubiosi.\n\n2. Uamasagaeriendereria, ubwiriyeYesu, ubwiriyeYesu, Yesuakandukuhabutseme, umubwireebiosi.\n\n3. Uamabyakubahaluholo, ubwiriyeYesu, ubwiriyeYesu, uamnamwikiririanomutima, Akandisyakulamya.",
"25. MUATSI OYO NI WA YESU": "CHARLIE D. TILLMAN/M. E. ABBEY\n\n1. MuatsioyoniwaYesu nimuatsiwakalamu Atiahekaebibi, bosananetubosi Moarihalubanzaluetu, monzonimuengekundu OyoniMulamiaWetu, YesuMuanawomungu.\n\nAleluya, aleluya, tumupipeMukama\nNabalailkabosibati, Yesunimuengekundu\n\n2. MuatsioyoniwaYesu nikagalakomnungu Luanzoolunilunene, lulabireluabahdu Tumukwa mehohakuhi, atuanzirekwenene Tuangabyabakwendabuwe, YesuMuanawomunungu.\n\n3. MuatsioyoniwaYesu ninzirayelubula Tulekenzirayebindu, nengumbuyomubiri Ewomunguiringebe, siharinobukoni Nahohatenoluholo, Nimuyiwomukama.",
"26. NASYABYA OKO PERO EYO": "J. W. V./ J. W. VAN DE VENTER\n\n1. Ekirokio lubanza kiasyasa, tuasyahangana yo, Yesu asyatswera abalaika, na ge, na we, na we.\n\nNasyabya oko pero eyo, nyerire momusasi wuwe\nNasitabakorina riage, Yesu moandamia.\n\n2. Akakira Yesu asyambako, akabuya buya, Emiaka itabahwa tuli yo, ne kiana kiembuli. Nasitabakorina riage, Yesu moandamia.\n\n3. Erigabana siriri kandi, eri luha rihwe. Ituahumula nabalikietu, erihikaka. Nasitabakorina riage, Yesu moandamia.",
"27. ERILAGA ERISIHIRE KWENENE": "C. H. G./ CHAS. H. GABRIEL\n\n1. Erilagarisihirekwenene, atisindie ndi syakwibirirwa, omuirimia amabya omonzira, OmuesiWuwe asyanyikolera.\n\nSinangakuibirirwa na hake, omobialaebiage, ngandisyakuwatako, Sinangakuibirirwana hake, IngyendiMulamia, ngakulembera. Sinangibirirwa sinangibirirw, Sinangibirwa na hake, na hake,\n\n2. Ngikiiraya erilagariwe, atisindie ndi syakwibirirwa, nomoabirabasyanyisigania, Tatavage akandisyanyibuka.\n\n3. Omugulunasyahikaendata, obilige buage bosisyuahwa, nasyatsemabosaneneriowa, Wasingyamugombewerikirirya.",
"28. TATA ASI": "S. M. I. HENRY/ E.O.EXCELL\n\n1. NyasiTatageasi, amalige walage gosi, moalola okueriagalwa, nakomutiwaKalvari, OkomutiwaKalvari.\n\nAsi, (Nyasi asi) asi, (nyasi asi) amalige wage gosi, gosi,\nAsi, (nyasi asi) asi (nyasi asi), akanyangirira gosi, gosi.\n\n2. NyasiTatawageasi, rilwala riomubiri, ebiosi ebikabika, kuitwe abana buwe, Tatawage asi biosi.\n\n3. NyasiTatawageasi, kiro lakironasyayaka, na syalola okoYesu, nasyalola okoYesu.",
"29. KA NI YESU": "T. O. CHISHOLM / CHAS H. GABRIEL\n\n1. Konindioyukahika, monyumbayesionde, Siawitenyumbaeyiwe, kutsengotsero, Nikwaakasondibawana bakonibosi, A wite amakamangi, koyunimunduwahi?\n\nKa ni Yesu, ka ni Yesu, Mugala wo Mungu,\nKa ni Yesu, omubuya, moatoka Kalvari. \n\n2. Konindikabungangaye, ebinywabiengebe, Ebibiebiomuhanya, akamubugira, Akasubayabaholi, akatokangetse, E hamuli awiteyo, koyunimunduwahi?\n\n3. Konindibakatwalayo, nabasodabangi, Konindiwapulayalo, olutehiluawe, Ulangiremunduoyo, okomsalaba, Basekabosi, koyunimunduwahi?",
"30. KANDI OMUATSI": "E. E. HEWITT/JNO. R. SWENEY\n\n1. KandiOmuatsiwaYesu nyanzire erioWago, Moayaho nangangkwirire mowa amaligewage.\n\nAkandiluanzoluaanzo luaYesu,\nNgandibwira mulikietu, eriganyirariomungu.\n\n2. KandiekinywakiaYesu ekiokialwalubulla, Ekikabyangoluseke Omonzirayage yosi.\n\n3. KanditupipeMukama Oyu wasa erilamia, Oyuwasyaswasaluba eriboholakihugo.",
"31. MONUWA OMULENGE": "HORATIUS BONAR\n\n1. Monuwa omulengewaYesu akanyibirikira. UselinoubaneOmuesiwage eriluhuka. MonasakoYesungokana byanyinaluhire kutsibu, Nabuenehobuluhuke obonabulamokihugo.\n\n2. KandiYesuakabirikira ubugenyotayawe. Nyiiriisokoeriengebe usekuingyeupulaye. Ubyeho kundu Omuesiwage lino nyikuhebutseme, Uluhuke okuebikaluhaya omtimawaWe.",
"32. SIHARI MUIRA NGA YESU KRISTO": "JOHNSON OATMAN, Jr./ GEO. C. HUGG\n\n1. SiharimuirangaYesuKristo, sihari, sihari. Ngoyoangatulamyakoebibi, sihari, sihari. Itwetuasyagendaelubula, mutseme, mutseme.\n\nItwetunemotsemaringi, bosana na YesuKristo.\n\n2. NogundiakatuanzangoMungu, sihari, sihari. NomundumuengengaYesuKristo, sihari, sihari.\n\n3. NindiakasyatutwalewuWe, niYesu, niYesu. Nerituhaebihembobingi, niYesu, niYesu.",
"33. YESU LENDERA NETU":"FANNY J. CROSBY/ SILAS J. VAIL\n\n1. Kristo ari werikota ulabire abeno, Omonzira yetu yosi Yesu lendera netu. \n\nLende. ra, hakuhi, lendera na Yesu,\n\n2. Situetsema nekihugo kutseeriyipipa, niwe utolere Kristo Yesu lendera netu.\n\n3. Tulabe mu misya yosi yobulige hanisi oko lukyo luerikota nasingira na Kristo.",
"34. MUESI WENDATA":"H. J. ZELLEY/ G.H.COOK\n\n1. Omuesi nekiro ni bibiri, sibietulungana hagoma. Kuti muKristo?\nLeka ebibi, Yesu angabyamuesi wawe.\n\nHa leluya netu tutseme, Yesu ka ni Mulamia Wage.\nMuesi wendata, muesi wendata, uangtakola muese wage\n\n2. Emiatsi yekiro ka ni mingi,siyitolere ko baKristo.\nTuamabibindula omutima, Omuesi iniakola kandi.\n\n3. Abandu bekiro ka ni bangi,muhindo wabo ni kiuna, Eyo ni rira nerirya meno, omuhindania woMuti4. Nawe tahi tahurikirira, libula nzira Yesu ase,\nGusa ebibi binduka lino, 0muesi ma.\nwendata takwama.",
"35. OMUKAMA UATOKIRE":"JOHN J. MC LAURIN/E. O. EXCELL\n\n1. Omukama uatokire bosana nage\nUimaye ebiosi biage, bianga bya biawe,\nUimaye ebiosi biage, biangabya bia We.\n\n2. O mukama mowagalwa bosana nage Mowaheka komuti bi bi biage,\nMowaheka okomuti e bibi biage.\n\n3. O mukama nyitsemire bona nage\nbona nawe, mubỉri sihire bosana nawe,\nmubịri asihire bosanạ nawe.",
"36. OBUNDU TUKARYA":"MARY A. LATHBURY/W. F. SHERWIN\n\n1. Obundu tukarya bukabuga, mubiri Wuwe bunika, lutehi olu lukatula, engulu yoluholo lua Yesu. \n\n2. Turi na wasingya O'Mulamia, bosana n'engebe yerikota ya lwa koKalvari Kobulige, bua Yesu Omugala womungu.\n\n3. UWe uri 'bundu buengebe, bualwa elubula, Yesu Kristo, tuhe oluanzo ngolo luawe, tukuanzire kundu omulamia.",
"37. AHO HARI ERITSEMA":"CLELAND B. MC AFEE/CLELAND B. MC AFER\n\n1. A ho hari eritsema, hakuhi noMungu,\nEbibi sibiri aho, hakuhi noMungu.\n\nOmuluhukia Wetu, moaIwa elubula,\nE rituleta yo, hakuhi noMu ngu.\n\n2. Sihari omuirimia, hakuhi noMungu,\nTuasyahindana naYesu, hakuhi noMungu.\n\n3. YeSu akatutwalayo, hakuhi noMungu,\nTukanódikinda Satana hakuhi noMungu.",
"38. OMULAMIA TUKASYAKUPIPA":"JOHN ELLERTON/ EDWARD J. HOPKINS\n\n1. 0mulamia tukasyakpipa, Erihana riawe ni ribuya,\nUtubikire ebiny wa biaWe, ituakulinda nerikuke nga.\n\n2. Omokiro tukujbuke Yesu, oko waWe sihali muirimia,\nUkoleraye 0muisi wetu, ekiakakala ekio kiengehe.\n\n3. Obusayiro bwetu ni Kristo, 0musibikia omobuliPe.\nOmuami Wetu uri mukulu, ututsumule nengebe yawe.",
"39. YESU NI MUANA WOMUNGU":"Mrs. LYDIA BAXTER/W. H. DOANE\n\n1. Yesu ni Muana woMungu, oyo abirituanza, Tuamabya tuamikirirya, tu kandi1ama li no.\n\nErina, ria Yesu (ria Yesu), erina rioMulaimia,\nTumuanze (tumwanze), ebiro (ebiosi) biosi, ni Muami muenge wetu.\n\n2. Tuyire rina riwe, muinene biro biosi, Ni erina rierilama, kumbe ua mikiri rya.\n\n3. Usabe koe 'rina riWe, uamabya nobulige, Akandikuha \"butseme, na kagala kane ne.",
"40. MUGENDI WE GALILI":"Mrs. C. H. MORRIS/Mrs. C. H. MORRIS\n\n1. Mohabya omundu 0ko ngetse, engetse (engetse) ni ya (ni ya) Gali(Galili.)li.\nEsi0ndeko mosiakwama Oyo, Muge(Muge) ndi we Galili (ndi we Ga lili).\nMoalibula ameso wabandu, abalema mobasiu ba, nabangi mobalama mo biala,\nBiomugendi we Ga lili.\n\nNage ka nangamwanza na kera (kera, na kera), omundu mubuya oyo, (omundu mubuya, mubuya oyo,)\nAbye Mulamia wage Yesu (abye ni wage,), Mugendi we Ga,lili.\n\n2. 0 mundu oyo ka moanyisonda, inabiritala kundu.\nEbironda biebibi bianyita, ka nabya omuhania.\nEnzira yiwe moyabanika, nebibi mobiabugirwa, nehamuli namaka angaha,\nWomugendi we Ga lili.\n\n3. O bundu buengebe burihahi, namagetse werikota?\nNedawa yamakoni wenoka, neriagaIwamisindo?\nSusondaye hali mulikietu, erilama rieri hano, ebiosi bíri mo biala bioyo, Omugendi we Galili.",
"41. ABIRIKINDA AKASYAKINIDA":"SALLIE MARTIN/JNO. R. SWENEY\n\n1. A birikinda, akasyakinda, 0muami wetu Kri sto.\nAbirikinda enzigu yetu, monzo ni muenge ku ndu,\nNetu baKristo tutseme, tupipe, Yesu Kristo,\nAbiritoka kwe nene, tumukwame twe bosi.\n\nMuase tupipe Mu kama, Owekihugo kiosi.\nAkagala ketu ni Yesu, omutoki webiosi.\n\n2. Abirikinda, akasyakinda, 0yu ni Muami we tu,\nN'abandu buwe nabo ni bahi? abakamukolera,\nIye ni Yesu Mụkama, 0mutongolia wetu,\nNabo bamabya baKristo, aboMungu wendata.\n\n3. Uabirikinda, ukasyakinda, Yesu ri mubu ya.\nAmami gosi bakasyahẹra, nikwa ukasyakota,\nNawe ukandisyahemba, abakwenene bo\nTuasyakusaba e ndata, uamuwania kundu.",
"42. MUNDU WAYESU UKWAME NDEKE":"T.O. CHISHOLM/ HAROLD LOWDEN\n\n1. Mundu waYesu, ukwame ndeke, ubye hakubi noyo'kuanzire,\nUmuhe lino ebiala biawe, enzira yiwe yangabya yaWe.\n\nYesu uli muenge, ngahika okuWe, kosan gwa nowahola erinyilamia, uri Mukama wage, Ualabire biosi, ngandikukolera lins, O Kristo owene.\n\n2. Yesu moayaho, nangakwirire, ebibi biage moaheka biosi,\nOluanzo luWe. nyikwamirelo, ndi 'mundu wuWe, waYesu Kristo.\n\n3. Engulu yiwe, nganditulayo, Erina riwe tu.. kasabario,\nSindiubaha 'bulige bosi, tukanditsema hago ma Naye.",
"43. MUAMI WAGE NGAKUPIPA":"JENNIE EVELYN HUSSEY/WM J. KIRKPATRICK\n\n1. Muami wage ngakupipa, tuabirikusima,\nNerio situangibirirwa, muti waKalvari.\n\nNerio situibirirawe, eriagalwa eriWe,\nNolua. nzo luWe lunene eyo ko Kalvari.\n\n2. Mobamuta omuisinda, nobulige bungi,\nMoyitetamuhambaho, moakinda luholo.\n\n3. Erina ria Yesu Kristo, tuyiketererio,\nNomusasi Oyo wuWe, akinatueraya.",
"44. UBYE NETU":"HENRY F. LYTE/WILLIAM H. MONK\n\n1. Ubye netu, nakagala kawe, netu situangubaha Satana,\nMomuirimia we kuhugo kino, uangabya'luseke luetu, Kristo.\n\n2. Uhye netu, nerihenia riawe, biro ni bike ebiekihugo,\nNabandu bangabinduka luba, uwe werikota, ubye netu.\n\n3. Ubye netu, Tata werikota, tuganiraye luholo lwawe,\ntukulinde komubiri waWe, Yesu Mulamia ubye netu.",
"45. NI WAWE NA WAGE":"E. B. HEWITT/ E. O. EXCELL\n\n1. Hari eribugira, ni riaWe, ni ria ge,\nrilusia tiebibi, ni riawe na ge.\n\nNi riawe uamaliga uamanza erilama,\nAngakukokia lino, ni riawe, ni riage.\n\n2. Olukimba lubuya, ni luaWe, ni luage,\nNomuyi henirie, ni WaWe na ge.\n\n3. Hari Tata enda ta, ni WaWe, ni Wage,\nHari gundi eyikwa, siwawe na ge.",
"46. TUPIPE MUAMI OWEKIHUGO":"Sir ROBERT GRANT/FRANCIS JOSEPH HAYDN\n\n1. Tupipe Muami oWekihugo, nakandi muangimba, tumusime Yesu.\nAkatulembera, akatubika, netu twangamusaba, neriha wasingya.\n\n2. Tubwire bandu omiatsi Wuwe, situluhe kandi, akaha kagala.\nIye ni nene, akatabala, muaha engebe yiwe, erilamiabandu.\n\n3. Awite maką kuilaba bọsi, noluano lwa Yesu, lualeta buholo.\nAbiri tuyira, mobana buwe, ngabagala be kundu,twangamukolera.",
"47. AMBALE OBUKAMA":"OLIVER HOLDEN\n\n1. Tasamalira kagala kerina risYesu,\nLeta akakira akobuami, mbale obukama,\nLeta akakira okobuami, ngambala obukama.\n\n2. Muase abalaikå bosi nebinanda bieno,\nTuhe obukulu oko Yesu, mbale obukama\nTuhe obukulu oko Yesu. Angambala obukama.\n\n3. Kumbe turiyo nabandi e riu nama yo,\nTuangabuga nomulenge oyu, ambale obukama\nTuangabuga nomulenge oyu angambala obukama.",
"48. NINDI ANGATULAMYA":"R. L. /ROBERT LOWRY\n\n1. Nindi aingatulamya, ni na Yesu iyowene,\nNiki kio kiangatuerya, gonomụsasi wa Yesu.\n\nUa matuwaniYeSu 0mula mia,\nTuabirikirirya, oko musasi wa Yesu.\n\n2. Alihire ebibi, gonomusasi wa Yesu,\nAmalusya lubanza, gonomusaSi wa Yesu.\n\n3. Uangahika hakuhi, OkOmusasi Wa YeSu,\nEyindi nzira siri, gonomusasi wa Yesu.",
"49. ATOLRRE":"GEORGE O WEBSTER/CHAS H. GABRIBL\n\n1. Atolere erinyitongolia, omobiala bienzigu Satana,\nYesu wetu angatutolera, sihari gundi wamaka atutolere.\n\nAtolere(Atolere kundu), Yesu wetu(Yesu Kristo wetu), Yehova noMukama, (Mukama)\nAngatolera lino Angatolera mungya, ni Alfa na Omega a tutolere.\n\n2. Oyu nindi wangatu tolera, wangatukindisya e Satana,\nYesu wetu angatutolera, abirilaba emhere atutolere.\n\n3. Atolere siaribirirawa, siariya • to esaa yobulige,\nYesu wetu ngayiketera Ye, akasondolaenzira atutolere.",
"50. AKALEMBERA":"ADA R. HABERSHON/ROBERT HARKNESS\n1. Omugulu wobulige akalembera, Nokondambi yeriluha akanyilembera.\n\nAkalembera, (kundu), akalembara, (kundu). Ebironendambi yosi akalembera.\n\n2. Ekirikierilengwako, akalembera, abirinyilamiakundu. Akalembera.\n3. Erilinda omukama, akalembera, amaha ayo wa yesu, akalembera.",
"51. EBIHUGO NI BIWE":"WILL L. THOMPSON\n\n1. Kumbe bihugo biosi biangabyabia yesu, kumbe andu bosi bamuanzire kundu. Ebihanda ebiosi   biangabya bia kristo. Oyo bita komuti akandisyakinda. Ebihanda ebiosi biangabyabia kristo. Ebiwe.\n\nEbihugo ni biwe, ni biwe, ebihugo biangabya bia yesu.\n\n2. Kumbe bihugo biosi biasi omukama, nesindi esiodeni nesionzigu nibya. Yesu atolerebo endambi ni ngihi. Engunga yangabugabuga iniasa mobitu. Yesu atolerebo endambi ni nguhi. Enguhi.\n\n3. Kumbe bihugo biosi biangasikia yesu, ebitsira ebiosi ne congo hagoma. Obunandi buhike nobupiri bosi. Abami nabagunda bangabya abuwe. Obunandi buhike nobupiri bosi. Abosi.",
"52. KA NYISIKIRE":"S.E.L./CHARLIE D. TILLMAN\n\n1. Kanyisikire erigalwa,bosana na yesu kanyisikire erisaba bosana na bandu.\n\nNyisikire, eritula, omuatsi wakri sio, erikolera omukama, okuisonda riwe.\n\n2. Kanyisikire erigenda,ngomukwenda wuwe,omobihugo ebiahali, amanyitu mayo.\n\n3. Kanyisikire eriteya, omubiri wuwe, erihangananakagala, monzira ya yesu.\n\n4. Kanyisikire erikunga,ababirihera, omo’nzira yenzigu yetu, yesu anzirebo.",
"53. ITIWE TURI BANA BOMUAMI MUNENE":"KNOWLES SHAW/GEORGE A. MINOR\n\n1. Itweturi ‘bana bomuanene, tuabirikirirya ‘binywa bia yesu, tualekire ‘bibi biekihugokino, tuabana ‘butseme buomulamia.\n\nTubwire ‘bandu, ‘binywa bia yesu, tutule omutsi wenzira yiwe Tusabe yesu neri na riwe, mungu asyalusya. Ebibibiosi.\n\n2. Mo’kihugo kino, muri ‘bandu bangi, ababirihera mo’nzira nyirbi, tuangasaba mungu baleke ebibi, tuangakangayabo ebinywa biwe.\n\n3. Enzira ya yesu ninzira yowene, muri eritsema,muri kagala, enzigu satana n’abalaika bayo bakandisyahera mo’nzira nyibi.", 
"54. KRISTO APIPAWE":"Tr. EDWARD CASWALL/ JOSEPH BARNBY\n\n1. Omugu werikya ngatang’eriahula, omukama yesu, kutse komubiri, kutse kwerisaba, kristo apipawe.\n\n2. Oko munguendata, ngatulago kandi, yesu apipawe, kamoaleta maha, moaleta nendihi, kristo apipawe.\n\n3. Ekiro kiobulige, ekirongaluha, yesu apipawe, akambirikira, inaswanyikunga, kristo apipawe.\n\n4. Akatambi ni kake, nyikole nomuhwa, yesu apipawe, tugese engano, yerire muirima, kristo apipawe",
"55. TUASYAHINDANA ELUBULA":"R.L./ ROBERT LOWRY\n\n1. Tuasyahindan'elubula, Oko wetu woMungu,\nAbandu babirianza,batsemire kutsibu tsibu.\n\nTuasyahindan'elubula, oko lusi lubuya olwengebe,\nAbandu bos1 batsemire yo, endambi yosi baneyo.\n\n2. Bariyo bakimba luimbo, obulige sibuliho,\nOluimbo lua Yesu Kristo, 0mukama munene wetu.\n\n3. Abayo balinamaka, sibeluala nerihola,\nEbibi biosi biamnahwa, sibiangatok'eringirayo.",
"56. ALELUYA":"J. MC G./ JAMES MC GRANA HAN\n\n1. Aleluya, Yesu moalwa muisi nda, tukasima Omulamia Oyu, eyisinda moyi .teta muto ka, Yesu ni Muami wabami bosi.\n\nTukapipa Yesu Kristo, Tukalinda Muami wetu, tugende mokihugo, tutu'engulu, na yekandibya netu.\n\n2.Aleluya, tutsemire ku YeSu, oyo watubohola kwenene, enzigu yetu Kristo moakindayo, Ebiro biomuliki biahwere.\n\n3. Aleluya, mukama aSyasa, tuytsinge komubiri WuWe, elubula eriluha siriri, 0butseme no buholo busa.",
"57. YESU MOARIHA":"Mrs E. M. HALL /JOHN T. GRAPE\n\n1. Yesu asi amaka wawe ni angaha, \"Usabe nerite ya\" ebio ni binywa biwe.\n\nYesu moariha lubanza luage, ebibi biabya bingi, Naye moeria biosi.\n\n2. Omukama ni kundu a. kagala kaWt, kakatoka mutima owakalire na bi.\n\n3. Ka singwite 0muira ngo Mukama wage, Imene ho hakuhi, naye akalembera.\n\n4. Ngakunda nomuhwa Alfa na Omega, erihika eriaWe rikaleta Obuami.",
"58. NENYU MUASE":"1. Nenyu muase, nenyu muase, nenyu muase lino.\nLino muangamuikirirya, muiki rirye Yesu.\n\n2. Akuanzire, akuanzire, akuanzire ku ndu.\nKumbe uabirimu minya, kua nzire kundu.\n\n3. Lwa koebibi, Iwa koebibi, Iwa koebibi lino.\nUasyabana obutseme, oko Yesu Kristo.",
"59. RIBYE RIBUYA":"JEAN PERRY/ MABEL JOHNSTON CAMP\n\n1. Nyasi erina erioMulamia eriahika eno kera, omulaika mualetario kera, erina eribu ya.\n\nRibye ribuya, ribye ribuya, erina rilabire ku ndu, riangabya ribuya, ribye ribuya,rina eria Yesu.\n\n2. Muenye erina erio ribuya moahola oko KalVari, ebibi biage bialeka oyo, iniagaIwa kutsibu.\n\n3. Mungu hana erina rio ribye endata kogosi, basyakukana embere siwe, abamuseka kera.",
"60. YESU KRISTO ATUANZA":"CHARLES WESLEY/S.B. MARSH\n\n1. Yesu Kristo watuanza, uri Mulamia wetu, Setani situanzire yikatukola nabi.\nYesu Kristo tuamasa oko wawe wowene,\nUtulamaye lino nomusasi gowene.\n\n2. Yesu Kristo Mulamia uatusondire kera; Tuamabya 'bandu babi, ulusaye ebibi.\nUtubise ho uli ahate no bulige,\nSituwite 'kagala, tuamasa, u tuhe ko.\n\n3. Engebe yerikota yikalwa oko wawe, utusulaye lino no'mutima mubuya.\nYesu twamakukwama, utukangaye ndeke,\nTuamaleka 'kihugo, tukuanze 'biro biosi.",
"61. SABA SABA":"B.R.W./EDNA R. WORRELL\n1. Saba saba akagala, Saba saba, siumbaye, uaagakinda esatana, Saba saba uangatoka.\n\n2. Saba saba mulikietu, Saba saba siumbaye, hatikana okomalwi, Saba saba akatoka.\n\n3. Saba saba asyaswasa, Saba saba ritolere, saba ngerisondariwe, Saba saba, yesu ane.",
"62. NYANZIRE ERIBYA HAKUHI":"JESSIE BROWN POUNDS/ CHAS H. GABRIEL\n\n1. Nyanzire eribya hakuhi, nomukama wage yesu, erimulolako nerimukama, nyanzire eribyaye.\n\nHakuni naye, na yesu kristo, nyanzire erisiba, erimulolako nerimukwama, nangabya hakuhi naye.\n\n2. Nangabya hakuhi na yesu, omugulu werilwala, erisaba neri mukwamirira, na syakota nayekera.\n\n3. Nyanzire erihika riwe, erinyitwala ewuwe, ahate obulige neririra okomuyi welubula.",
"63. YESU AKATUSONDOLA":"G.A. YOUNG\n\n1. Omo nzira yiweyitunganene, yesu aka tusondola, esaa yobulige, esaa yobutseme, yesu akatusondola.\n\nAbo mombeho nobulige, nabandi nni bia bakagalawa, yehova akasondola bosi, omo kiro neritungi riosi.\n\n2. Ekiro kiobulige neriagalwa, yesu aka tusondola, ekiro tutelangira muesi ndeke, yesu akatusondola.\n\n3. Tuamalengwako nenzigu gu satana, yesu asya tusondola, tuangakinda enzigu namaka wuwe, kosangwa akasongola.",
"64. OMUKAMA YESU":"JAMES MONTGOMERY/ SPENCER LANE\n\n1. Omukama yesu unyilamaye, lero si nyitoge mo’nzirayawe. Unyiwate ko’biala, unyihire hakuhi, sinyikole nabi, ndi’munduwawe.\n\n2. Bindu bie kihugo bianganyitebya, omukama yesu unyilamaye. Unyiringekanaye, bosa na na kalvari, sinyibirirawe, oluanzo luawe.\n\n3. Amakoni mangi akanahika, neriendererya rio ria satana. Utuhe’mengewawe, n’omuhwa werisiba,  oluanzo lo luawe, ni luerikota.",
"65. TUKWAME YESU":"1. Tukwame yesu endambiyosi, sihari muiri muirimia mo’nziranyiwe, obutseme kutse bulige, yesu wage alabire biosi.",
"66. NGATSEMA OMUIYE":"B.O. E./ E. O. EXCELI\n\n1. Ngatsema kundu oko Yesu, kusangwa akinanyanza,\nMulenge wuwe akowana, kumbe_nangmulolako.\n\nNga(Nga)tsema omui(tsema)ye(omuiye), nga(nga)tsema omui(tsema)ye, (omuiye).\nLukogo luwe luasire kera, nyltsemire Omulye.\n\n2. Yesu kamwanyisonda sonda, omugulu nabyamubi,\nMoanyilsia kwebibi biage, linomuli obutseme.\n\n3. Oluanzo luwe ni lubuya, 1lukanyitimbako lino,\nYesu ari hạgoma nage,erinyilembera hosi.",
"67. KUNO TURI BAGENDI":"Arr by P. A. Clark/CA. TINDLEY\n\n1, Kuno tu. ri bagendi, turi banduba Yesu,\nBaka tukwa ekiniga nerituendereria,\nNikwa ho Yesu ari sihari amalolo,\nYesu asyatuhira ho habuya(habuya.)\n\nElubula ni 'muyi wetu, Yesu Kristo ni Mulamia,\nturi nobutseme biro biosi, n'omuatsi wetu akandisyuwana.(wasingya.)\n\n2. Omubiri wa Yesu, ni mubiri munene,\nSitoWe bikateba ya biebindu bierihọnda,\nTuangakinda Satana nomuyari woMungu,\nnetu akagala ketu ni Yesu.(ni Yesu.)\n\n3. Erihika ria Yesu, ati riri hakuhi,\nKa tuasyowa omnulenge Womulaika munene,\nN'engunga yo yoMungu ikandisyatubukia,\ntuasiahindana 'ndata noMukama (Mukama.)",
"68. INGYE NYANZIRE MUATSI":"C. H. G. /CHAS H. GABRIEL\n\n1. Ingye nyanzire 'muatsi wa Yesu, ni Mukamawakwenene, nikwa akandisyahika lu ba, Tuasikala naye kundu.\n\nSihari bulige neriagalwa Oko muyi werikota, nasyahangana ha. kuhi naye; 0. muka Webihugo.\n\n2. Biro ni bike monaki. hugo, O'Mukama asya hika, eriIwalayo neriSwaluha, Sibiehik'eyo na hake.\n\n3. Biro ni bike bieritulayo, engulu ya Yesu Krist0, tuhangane tuyi tsinge lino, Omuirimia akahika.",
"69. IRI EKIHUGO KIOWENE":"S. FILLMORE BENNETT/ JOS. P. WEBSTER\n\n1. Iri ekihugo kiowene, ekia Tata wetu oMungu, nemukoko , tyaho wetu tuasyasiba naye buholo.\n\nTuasyahi(Tuasyahi)kabolo(kabolo) Okomuyi wa Tata wetu(Owetu,), tuasyahi(tuasyahi) ndanayo(ndanayo), Oko muyi mu buya ku ndu.\n\n2. Tuasimba oko muyi 0yo, esionyimbo sia Yesu Kristo, ahate bulige buke, kutse eriIwala 'makoni.\n\n3. Wasi ngia ko Mukama Yesu, oyo watuholera kera wasiagya koMulamia we . tu, Oyo watulusya koebibi.",
"70. MUNGU MUBIRI WAGE AHWERE":"FANNY J. CROSBY/ JNO. R SWENEY 1. Omugulu mubiri wage ahwere hano ngandihika elubula habuya, nasyamuminya omutongolia wage luba, naye asyatsema erinyikokia. Nasyami(nasyaminya)nya Yesu Kristo, kusangwa abirinyitongolia, Nasyami(nasyaminya)nya Yesu Kristo, nesio ngolu omobiala biwe. 2. Abakristo bengi bangendire e muliro, bakatulinda nobuholo buwe, tuasyatse hagoma emuliro wa Yesu, nikwa nyanzire Mukama ko bosi. 3. Nganditsema erilangira obusu buwe, noluanzo oluri komeso wuwe, nobuenge buwe buabiri nyilamia.",
"71. EKIRO AKASYATUENDA":"J.M.B./ J.M. BLACK 1. Ekiro Yesu akasyatuenda abandu buwe, nengunga yo Mungu ikasyatubuwa, abandu buwe bosi bakandisyalwa'mwisinda, tuasyahindana eria elubula. Nasyabya (Nasyabya elubula wasingia), yo elubula, hagoma(hagoma na)na Yesu Kri(Yesu Kristo wasingia)sto, Nasyabya (Nasyabya yo elubula) yo elubula, ngandira yosi. 2. Mungu amatubirikra omomitima yetu, sianzire abandu bakasyahera, tumaleka ebibi biosi bya balimu babi, Yesu angatulamia lino lino. 3. Ego tukole omubiri wo Mungu goluba, Omwirimia akasyahika luba, n'a bandu bangi sibasi omulamia wetu, tubirikirebo balame lino.",
"72. MOMABOKO WA YESU":"FANNY J. CROSBY/ W H DOANE 1. Momaboko wa Yesu, owerikota, Oyo awite 'kagala, akeritulamia. Oyo ni Mungu wetu, oyo atuanza kera, Atuma O'Mulamia eririha ebibi. Nerilamia erinene, eriorio Mungu wetu. 2. Momaboko wa Yesu, ahate 'bulige, Setani sianganyitoka, yikubaha Mukama, Omulamia asyasa, ituaya naye eria, Ahate erihola, kutse eriswagalwa. 3. Momaboko wa Yesu, ahate obuba, ahari erihenia rio rio Mulamia wetu. Kumbe twamakw' omu hwa we ri mu langirako, Atuansya mulangira, nomutima mubuya.",
"73. EBINYWA BIENGEBE":"P.P.B./ P.P. BLISS 1. Akandi wanganyibwira, ebinywa ebia Yesu, Ebisihire kwenene, ebinywa ebiengebe, Ebinywa bilabire ebiosi ebia bandu. Nibiengebe, nibiengebe, ebinywa bia Yesu Kristo. 2.Kristo abiriha bosi, ebinywa ebiengebe, Akabirikira lino omundu webibi, Akakuhabuyira butsera erigula. 3. Engulu yowene yiwe, ebinywa ebiengebe, Bikaleta obuholo, ua ma mui kiriria. Ogundi uangalamia siari ho nomuguma.",
"74. UASE MUAMI MUNENE":"CHARLES WESLEY/ FELICE GIARDINI 1. Uase muami munene, tupipe erina riawe, tukusikie tatawerihenia, uwe 'bugirire, uangaronga kandi, Muami wetu. 2. Uase Mulamia muenge, uambale muyari wawe, uangatowa, tunemukusaba, utuhe kagala; kirimu kio Mungu, utueraye. 3. Mungu tukupipire, tuangakusikia kwenene, uri muenge tuangakulangira, eyo mo 'lubula, O'Mukama wetu, Aleluya.",
"75. ERIHIKA ERIA YESU":"J.H. HOPKINS 1. Erihika eria Yesu, moriabya mo buera biosi, muabutwa mo nyumba ye sionde, Yesu amuami wetu. Yesu o'Mukama wasingia tukatseme okuwe, tuamabya nengebe busana nerina eriawe. 2. Muabutwa ngomundu weno, nomubiri weriagalwa, Asyatabala ngo'Muami wekihugo ekiosi. 3. Mobaleta erihitia, abamenge wekiendata, Netu tukaleta erisaba rietu o'Mungu.",
"76. MUNABWIRE":"Rev. JOSEPH MOHR/ FRANZ GRUBER 1. Munabwire, Yesu Kristo, muabutwa ngomwana, Mulamia wekihugo kiosi, Yesu Kristo mubuya kundu, abirituwania, Yesu mulamia wetu. 2. Towe 'muatsi, wobuholo, mulamia asire, erituleta eritsema, ne'siongebe esierikota, tumuanze no'mutima, Yesu Mulamial wetu. 3. Tukatsema, Aleluya, Mulamia owene, tumukwame endambi yosi, tumusabe nomuhwa gosi, erihenia ko'Mungu, Yesu Muamia moasa.",
"77. OBUTSEME BUAHIKIRE":"ISAAC WATTS/ G.F. HANDEL 1. Obutseme buhikire, o'Mukama 'sire, Ase momitima yetu, ni Muami wa bami bosi, tumusikaye lino(Tusikaye Yesu), Alengire 'bindu biosi(Tusikaye Yesu), Alengire, alengire 'bindu biosi. 2. Obutseme buhikire, busana na Yesu, muase abalaika bosi, muase abandu hanisi, tupipe o Mulamia, tumupipe omulamia, tumupipe, tumupipe omulamia. 3. Akabugira ebibi, nomusasi wuwe, Abirilusya lubanza, olo luabya oko bandu, atuhire omuinda, abirituha omuinda, atuhire, atuhire omusasi.",
"78. MUASE ABAKRISTO":"1. Muase baKristo, ababirimuaAza, muase Oko Yesu, ka tuangamukenga, tungerera ni Muami Owabalaika.\n\nMuase tuangamupipa,muase tuangamupi pa, muase tuangamupipa Ye Yesu Kristo.\n\n2. Muimbe abalaika muimbe nobutseme, muimbe imwe abosi abelubula, tuhe ko Mungu erikapipa kundu.\n\n3. Omukama wetu, ųnemukusikya, eri na eriawe riangabya inene, Myngu munene, ka n Muami waBami.",
"79. MOLUKAHIKA 0MOKIRO":"E. H. SEARS/ R.STORRS WILLIS\n\n1. Motukahika omokiro luimbo oluabalaika. buholo oko kihugo obubuya ko bandu.\nHulikirira omulenge, oWakahula Ye Yesu. A mulamia abiributwa, eri riha ebibi\n\n2. Oko mirongo yobulige engulu eyi ikasa, Hangana gusa eririra hambe Yesu Kristo.\nImanuel erina riwe ni Mungu hagoma netu. Amaha ayo akaleka, abalaika ibimba.\n\n3. Omulamia oyo moahika oko kiro ekiakera, Moahira ebiala biamaka oko kihugo kino.\nTahira ebiala okuitwe, ituabana erilama. Ekihugo kiangowa kandi,mule nge wa Yesu.",
"80. TUANGOWA ENGULU EYI":"C. WESLEY\n\n1. Tuangowa engulu eyi, erihenia koYesu, obuholo nobubuya, biahika 'kiro ekio. Tutsange abandu bosi,\nSetani abirikindwa,tutseme nabalaika, Yesu waBetelehemu, tutseme nabalaika, Yesu waBetelehemu.\n\n2. Kristo Muami werikota, moabutwa mo 'kihugo, moaleta oluanzo luwe, n'obuholo ko bandu. Kristo moahị ka enoka,\nYesu oMulamia wetu Mungu atugenyera, moatutumira Mula mia, Mungu atugenyera moatutumira Mulamia.\n\n3. Wasingya koMuami wetu, mundu atunganene, moaleta ekiakakala n'engebe yerikota. Moalusya lubanza luetu,\nMoaliha ebibi bietu, Muami moabutwa eno, eritutwala Muami moabutwa eno, ertutwala ewuwe.",
"81. TUTULE OMUATSI WA YESU":"GEORGE W. DOANE/ J. BAPTISTE CALKIN\n\n1. Tutule mwatsi wa Yesu, ehosi monakihugo, luholo lwa Yesu, luatokire olubanza.\n\n2. Tutule mwatsi wa Yesu, oluanzo Iwa Tata wetu, Moatuma Mugala Wuwe, erilamia ekihugo.\n\n3. Tutulę mwatsi wa Kristo, oko bihanda biabandu, Bakalinda mulenge, womukangiriria wuwe.",
"82. NATSEMIRE KIRO EKI0":"P. DODDRIDGE/ E. F. RIMBAULT\n\n1. Natsemire 'kiro ekio nikiriraya Mulamia, Moanyilusya koamalolo, moanyerya koebibi biosi.\n\nMoatuka ngya eriSaba neritsema 'biro biosi, Tu. tseme, tutseme, Yesu moatuerya koebi bi.\n\n2. Sihari 'gundi Mulamia, ni na Yesu iyoWene, Ni mubuya, anato ka, amaluSya oluba nza.\n\n3. Abiririha ebibi, abirikinda luholo, Moalubuka omuisinda, abirikinda Sata na.",
"83. ENGULU YERILAMIA":"J. M. D./ J. M. DRIV ER\n\n1. Engulu yerilamia unyibwire ka ndi,. engulu yangaswekia, unyibwire kandi, abalaika ka basiyo, Abalisia bakowago, nawe uangikiririago, Engulu ya Kalvari.\n\nUnasi(Engulu yerilamia) siwa si(Engulu yerilamia). Kumbe uasi(Engulu yerilamia), Omundu wa Kalvari.\n\n2. Engulu yerilamiaSegera hakuhi, engulu yangaswekia, ikinalamaya,amagetse owengebe, Obundu obuerikota, bikinakubirikira, Engulu ya Kalvari.\n\n3. Engulu yerilamia. ni na Yesu Kristo,ngulu yeriswekia, uamatendikwama, Elubula lukalinda, bayisogawa na Kri sto, abakimba oluim bo, Luenguu ya Kavari.",
"84. KA NABIRIGULWA NA YESU":"FANNY J. CROSBY/ ROBERT LOWRY\n\n1. Ka nabiriguIwa na Yesu, ekiana ekio kiembuli, Omusasi abiritoka, ndi muana Wuwe na kera.\n\nNi Ye(Ni Ye, Yesu), Yesu(Ni Ye, Yesu), obuguli ni musasi, (Ni Ye, Yesu) kia na kiembuli, Abiringira mo WuWe.\n\n2. Nyitsemiré muesi wa Yesu, nerihenia riwe riosi, Ngasaba inyi.nemutsema, ndi muana wuwe na kera.\n\n3. Nyasi nasyalola ko Muami, nasyahangana endata, Ekinywa kiwe kikalaga, kikakinda neSatana.",
"85. ERINA RIWE YESU":"P.P. B P. P. BLISS\n\n1. Erina riwe Yesu Omugala wo'Mungu, Ahika no kera erilamia ekihu go.\n\n2. Moaheka esisoni neriagalwa riomuti, Eririha e bibi, Aleluya mula mia.\n\n3. Omukulu asyasa. erie nda abuwe, Neyo tuasimba kandi, Aleluya omula mia.",
"86. ALUBUKA":"R. L./ ROBERT LOWRY\n\n1. Abya omoisinda, Yesu Mulamia; Mobamuta muyo, Omukama.\n\nMoalwa omoisinda(moasuba), moakinda esionzigu siwe, (moakinda), moakinda oluholo n'eyisinda, moasinga enzigu yetu\nSetani,moasuba(moasuba), moasuba(moasuba), Yesu Kristo moasuba.\n\n2. Mobamuteyaho, Yesu Mulamia; Baluha buyira, Moalubuka.\n\n3. Nindi ari ngaYe, Yesu Mulamia; Ni Muami wabami, Omukama.",
"87. KRISTO ABIRILUBUKA":"CHARLES WESLEY/ HENRY CAREY\n\n1. Kristo abirilubuka, Aleluya.\nMuangimba abandu bosi, Aleluya.\nMutseme a balaika, Aleluya.\nMuimbe elubula nekihugo, Aleluya.\n\n2. Mobateyaho buyira, Aleluya.\nKristo moakinda lifero, Aleluya.\nLuholo moluakindwa, Aleluya.\nKristo moakingula elubula, Aleluya.\n\n3. Omuami aneho kandi, Aleluya.\nEriswagalwa siriri, Aleluya.\nMoatuhole ra kera, Aleluya.\nNa lino anemutusabira, Aleluya.",
"88. ERISIASA RIA YESU":"H.L.TURNER/ JAMES MC GRANAHAN\n\n1. Rianganabya muitungi kutse mokiro, erihika ria YeSu Mulamia wetu, akandihika neritutwala eka, rikota nayeyo.\n\n2. Tuasy'imba Hosana ko Mukama wetu, Oyo Watuholera komusalaba, akandisyasa nerihenia rinene rituletera maha.\n3. UnaSikire erigenda endata, Mulamia amakubirikira lino, Kristo a akueya inione muteya, Syabaakakira.\n\nOmukama Kristo tubye nerikuimbirira, uasyaswasa Haleluya, Haleluya Amen, Halelu ya Amen.",
"89. ASYAHIKA KANDI":"M. J. C./ MA BEL JOHNSTOCAMD\n\n1. Simuluhe, bandu baKristo, mulangire Yesu asyasa, mo kihugo muri mwirimia, bakalinda ekiakakala kiwe.\n\n Asyahika kandi, asyahika kandi, ni Ye Yesu Kristo oyo itawa. Asyahika kandi, asyahika kandi, anemwendisyasa neriheniariwe. (eriwe.)\n\n2. Omuirimnia, abya munene, ebibi biatu kindano, nikwa lino twabirilama, nakandi asyatutwala ewuwe.\n\n3. Tukatsema, tuabirilama, tukatsena Yesu syaSa, tuangatula engulu yiwe, tuangabwira bandu ko Yesu ne.",
"90. KA RIOWENE KUNDU KUNDU":"Mrs. LOUISA M. R. STEAD/ WM. J. KIRKPATRICK\n\n1. Ka rioWene kundu kundu, uamikirirya Yesu;\nUamikirirye 'mibuge, yoMulamia wetu.\n\nYesu, Yesu, namabianza, nabirikwanza kundu,\nYesu, Yesu, ka ni 'muira, namnakusima lino.\n\n2. Ka riowene kundu kundu, muamaleka ebibi,\nImuabana esiongebe, n'obutseme kwenene.\n\n3. Kariowene kundu kundu, uamaminya Ye Kristo;\nUamainya kuasikala, hagoma netu eno.",
"91. OMULAMIA YESU KRISTO":"C.F.O.\n\nOmulamia, Yesu Kristo, akanyilembera 'biro biosi,\nEritungi n'omokiro, akanyilembera'biro bio si, biosi,\nAbirinyilamia neriganyira riwe, abiriny1gula nomusasi,\nIngye ndi monzira eyo yelubula, omu 'muesi goMungu.",
"92. OBUHOLO BURI MOMUTIMA":"Mrs. W. L. M./ Mrs. WILL. L. MURPH Y\n\n1. Obuholo buri momutima wage, ObutaIwa mo 'kihugo, ni buholo bua Yesu Mukamna wetu, ni 'buholo bue ri ko ta.\n\nTu(Tumukwanirire)mukwamiri(tumukwamirire)re,\nYesu Kristo(Omulamia ni Yesu Kristo), Tu(Tumukwanirire)mukwamiri(tumukwamirire)re,\nMua mi wetu(Muami wetu ni Muami wetu), sia(siangatusiga)litusigana(kasiangatusiga)ya,\n monzo ni muenge(monzo ni muenge, muenge), Yesu siarindisyatwibirirwa(Yesu Kristo siaribirirawa), ni wasingya (niwasingya).\n\n2. Omubiri wetu ni 'nyumba ya YeSu, turi bagendi hanisi, nikwa asyatuenda nerihenia riwe, tuasyakota elubula.\n\n3. Tukandimupipa Omuka ma Wetu, Muenye ekihugo kino, tuangamukolera nomutima gosi, Yesu uri omubuya.",
"93. ITWE TUAMABANA MUIRA":"JOSEPH SCRIVEN/ CHARLES C. CONVERSE\n\n1. Itwe tuamabana, Muira, Yesu Kristo Mulamia, Moaheka ebibi bietu, amatuha butseme.\nTuangamusaba 'kagala, asi 'mitabu yetu, Ni Mulamia muenge kugdu, Yesu Kristo ni Muira.\n\n2. Tuabya turi nobulige, n'enzira ikalire, Yesu akanditulamia, nakagala kanene.\nSituangaluha na hake, akandituWatikya, Tumusabe biro biosi, Yesu Kristo ni Muira.\n\n3. Mungu moakola kiowene, moatuma Muana wuwe, Nerilamia ko muIimu, Yesu Kristo ni Muira.\nTuasyasoker'ewa Tata, ahate nobulige, Tumutualire abandu, bangabya bana buwe.",
"94. KINGULA AHIKEMO":"H.D. C./ HARRY D. CLARKE\n\nOko lukyo oIwomu tima, omulamia akalinda,\nSurimowa, Yesu Kristo, kingula ahikemo.",
"95. HARI MUNGANGA MUNENE":"WM. HUNTER/ J. H. STOCKTON\n\n1. Hari Munganga munene, ni Yesu, Bwana YeSu. Akasonda erilamya a bandu bobulige.\n\nErina ria Yesu riri na kagala kalabire, Kalabire komena, gUsi wekihugo.\n\n2. Ebibi biawe ni bingi, Yesu, inialusyabio. Uikiriraye ku Yesu, nerio uabirilama.\n\n3. Yesu siaribirirawa, akandisyaswatuenda. Tumukwame 'biro biosi, nomutima mubuya.",
"96. UAMATAMBAKI NAWE":"FRANCES R. HAVERGAL/ P.P.BLISS\n\n1. Enyumba ya Tate wage nerihenia ria yo, Na sigabio, nasigabio, e rikusonda eno.\n\nNaha naha engebe yage, Uamatambaki na we?\n\n2. Monalusya ka wage erisangani bwa, Erilama, ne ribugira, erikuha ngebe.\n\nBindu ebindu nalaleta, Uamaletaki na we?\n\n3. Monaheka e riagaIwaria Kalvari ke ra, Erikulusia okuịtsanda rie. kihugo kino.\n\nMonakuhekera luhol0, Ua maambekeraki?",
"97. UASE YESU":"HARRY D. CLARKE/ HARRY D. CLARKE\n\nUase Yesu momutima, momutima wage Yesu,\nUase lino, uikaleho, enyumba yawe Yesu.",
"98. YESU UTUIKALAYE":"FANNY J. CROSBY/ W. H. DOANE\n\n1 Yesu utuikalaye, monzira nyibuya, tukukwame hakuhi, nakagala kawe.\n\nHakuhi, na Yesu, tuikale hakuhi, tusikaye erina, riOmulamia wetu.\n\n2 Utukangiriraye, muatsi werisaba, utusuraye lino, noluanzo lunene.\n\n3 Yesu tuamakukwama, nomutima gosi, tuka ndibwira bandu, muatsi werilama.",
"99. KOMUSALABA":"P. H./ PAUL HUTCHENS\n\n1. Komusalaba, komusalaba, Kristo moatuholera, Yesu moarihalubanza luetu, komusalaba.\n\n2. Namukwamire, namukwamire, Yesu mubuyirire, AkandisyaSa nerisyatuhemba, tukwame Yesu.",
"100. YESU MOAHIKA ENO KERA":"WM. R, NEWELL/ D. B. TOWNER\n\n1. Yesu moahika e no kera, moariha ebibi biabandu, ka muta omusasi wuwe, eKalvari.\n\nTuabana butseille aho, ekiro Imotuamuikirirya, omusaSi wuwe moatueria eKalvari.\n\n2. Ehibi bietu ni binene, tuabutwa mobandu babi, kumbe tuamikirirya Yesu waKalvari.\n\n3. Yesu ari hago ma netu, tuwite 'kagala koMungu, nindi wangatukinda lino eKalvari.",
"101. BOSANA NAKI NABIRIMUANZA":"I. A. K./ IDA A. KORITZ\n\n1. Bosana naki nabirimuanza, Ye Yesu Omuami? Bosana naki nabirimuanza, ngandikubwira lino.\n\nKosangwa abirinyiholera komuti,\nEkio kialekire namuanza, Yesu moanyịholera.\n\n2. Bosana naki ngandimupipa, Ye Yesu OMungu?\nBosana naki ngandimupipa, ngndikubwira lino.\n\n3. Bosana naki ngandimulinda, Ye Yesu Omuami?\nBosana naki ngandimulinda, ngandikubwira lino.",
"102. HAKUHI NA YESU KRISTO":"FANNY J. CROSBY/ Mrs. J. F. KNA PP\n\n1. Hakuhi na YeSu Kristo, namasa hakuhi.\nHakuhi noyo wahola, namasa hakuhi.\nHakuhi noyo wasaba, hakuhi noyo moasekwa,\nHakuhi noyo moagaIwa, ngahika hakuhi, ngahika hakuhi.\n\n2. Hakuhi nerigenyera, namasa hakuhi.\nNomuhwa werimusaba, namasa hakuhi.\nErimu pipa Yehova, oMugala oyo muanze,\nNyanzir'eribya hakuhi, ngahika hakuhi, ngahika hakuhi.\n\n3. Hakuhi noluanzO luWe, namasa hakuhi.\nNerimulinda namaha, namasa hakuhi.\nHakuhi nabalengire, eriàmbala kakira,\nE.rilolako Muami, ngahika hakuhi, ngahika hakuhi.",
"103. YESU KRISTO MOAN YANZA":"ANNA WARNER/ WM. B. BRADBURY\n\n1. Yesu Kristo moanyanza moaliha olubanza, Ingye ndi 'mu ndu molo naye ni wakagala.\n\nYesu nzire, abandu bosi,\nMonzo ni muenge, ekio ni wasingya.\n\n2. Yesu Kristo Mukama unyilamaye lino, Namaleka Satana n'ebibi biosi biage.\n\n3. Yesu Kristo uasyasa, uasyanyitwal'ewawe, Ngandikola 'mubiri, i nakulindirira.",
"104. ASYASWASA ASYASWASA":"W. O. CUSHING/ Dr. GE0. F. RO0T\n\n1. Asyaswasa, asyaswasa, omulamia wetu, asyatwala, asyatwala, abandu buwe.\n\nTuasyatsema kutsibu, ria ewOmungu,\n Nerikota, ewuwe, siturilwayo.\n\n2. Imwe bosi muangaminya,omuatsi wa Yesu. Muangakwama nomutima, imuasyalama.\n\n3. Yesu Kristo asyaswasa, ekiro situasi, umulinde, mulinde, ngOmuami wawe.",
"105. YESU ANZIRE ABANA":"1. Yesu anzire atuna, abosi bekihugo,\nBayira n'aBasungu, anzire bosi kundu,\nAnzire ba na bo si beki hu go.\n\n2. Yesu noahola koWuti, neritungolia bandu,\nBayira n'aBasungu, ni Mulamikundu,\nWabandu bo si ba bi bekihu go.",
"106. KRISTO IKERE OMUESI WAGE":"EL NATHAN/ JAMES MC GRAYNAHAN\n\n1. Kera nabya hali koMungu, nabya kolubanza, Nikwa Yesu moanyi ge nyera, nyilamire lino.\n\nKristo ikere Omuesi wage,\n(Kristo ikere Omuesi Wage)\nErilama kwenene eria Yesu Kristo.\n\n2. Tukalinda oyo wahola, oyo walubuka, Alengire aba ndu bosi, ni Mukama Yesu.\n\n3. Sihari erina ngariwe, sihari oluanzo, Sihari obuholo nibia, ngo bua Yesu Kristo.",
"107 OBUTSEME BURI OMOMUTIMA":"GEO. W. COOKE\n\n1. Obutseme buri mo mu ti ma, obua Yesu, obua Yesu, kosangwa Yesu abirinyilamia, wasingya ku Yesu.\n\n2. Kosangwa ingye ndi muana wa Yesu, owa Yesu, wa Yesu, abi ririha olu ba nza luage, wasingya ku Yesu.\n\n3. Tukule omubiri WOmukama, wOmuka ma, wOmukama, tutulengulu yiwe ko bandu, ngulu ya Yesu.",
"108. UPIPAWE YESU":"SAMUEL MEDLEY/ MOZART Arr. LOWELL MASON\n\n1. Omukama Yesu usikibawe lino, upipawe biro biosi. Kristo werihenia, kumbe tuasi erikupipa, nga balaika bali endata, upipawe Yesu, upipawe Yesu.\n\n2. Tukayiketera omusasi wa Yesu, sihali eyindi nzira. Yeriya elubula, akeraya ebibì bietu, nt rituyira ababuya, upipawe Yesu, upipawe Yesu.\n\n3. Ekiro kikandisyasa kumbe ni luba,tuasyaya eka ewetu, Ituasyamulolako, neriimba luimbo lubuya, nababugirire abosi upipawe Yesu, upipawe Yesu.",
"109. NI WASINGIA, YESU AN YANZA":"P.P.B./ P.P. BLISS\n\n1. Tata wage ka ari hakuhi, ekitabu kikambwira ekio, emiatsi eriswekera mingi, owalabire Yesu anyanza.\n\nNiwasingia Yesu anyanza, ni wasingia ka anyanza,\nKa anyanza oko kalvari, akuanzire nawe.\n\n2. Kera nabye mo kibi kinene, isinyitolere buami buwe, nikwa oluanzo luwe lunene, moluanyiyira mo mundu muhia.\n\n3. Konange nawe tungakolaki, itwe abanze bobuami buwe, tuangasonda omubiri wuwe, eritendi biha kutse kindi.",
"110. YESU MOAHOLA OKO MUTI":"E.A. HOFFMAN/ J. H. STOCKTON\n\n1. Yesu moahola okomuti, moahola eritulamia, Omusasi wuwe mutika, eritueria.\n\nTuyire rina riWe, muinene ndambi yosi.\nEria ria Ye. su ri0wen:, rikalamaya.\n\n2. Yesu moaliha olubanza, ritolere ituikirirya, uase ku Yesu munawi re, monasesene.\n\n3. Yesu akandikala netu, akasikala biro biosi, umuhe Omuti ma wawe, akandieryago.",
"111. 'BANDU BOSI BAMINYE YESU":"HARRY DIXON LOES\n\n'Bandu bosi baminye Yesu, Yesu Kri sto, ko(Yesu Kristo Omulamia)muti ahola bosana nabo, abosi bangamukiriria.",
"112. MUATSI OYO WA YESU":"1. Muatsi yo waYesu, ni 'muatsi werilama Ni muatsi wakagala, kerilamya kihugo.\n\n2. Ni muatsi wobutseme, ni 'muatsi wobutseme, Ni 'muatsi wobutseme, muatsi oyo wa Yesu.\n\n3. Ni kagala koMungu, ni kagala koMungu, Ni ka gala koMungu, akatulamia nako.\n\n4. Kumbe uamikirirya, kumbe uamikirirya, Kumbe uamikirirya, ni Mulamia wetu.",
"113. YESU UNYIHIRE HAKUHI":"FRED WOODROW/ CARL FISCHER\n\n1. Yesu ulabire biosi, unyihire haku hi,\nSinyibye ngakuibıri.rwa mo muirimia hanisi.\n\nYesu ngandikwama, Yesu ngandikwama, ngandikwa ma hakuhi.\n\n2. Uwe Kri sto uatokire, erikunga engetse,\nNerihunga rikakowa, biosi mo biala biawe.\n\n3. Ebiengebe noluholo, ni bieha muli yawe,\nUnyilembere muitebia, sinangatikatika.",
"114. YESU MOANYIGENDERA EKALVARI":"P. P. BILHORN\n\nYesu moanyigendera Kalvari,\neKalvari, Kalvari, erilusya 'kibi.",
"115. HARI EYISOKO YOSWIRE":"WILLIAM COWPER/ LOWELL MASON\n\n1. Hari eyiSoko yoswire, nomusasi wa Yesu Kristo, Noyo anzire rihenia, angahika ku Yesu.\nAsyalusibwa okoebibi, n'engmbuyezira nyibi, n'oyo anzire rihenia, angahika ku Yesu.\n\n2. Itwe tilnemotsema ringi, tuabiribana Omulamia, Ari nakagala kanene, kerikinda Satana\nYesu moakinda erihola, moalubuka omoisinda, ari nakagala kanene, ke rikinda Satana.\n\n3. Oyo abirikwa komuti, akandisyahika akandi, Nerisyatutwala eWuWe, a.hate n'obulige.\nTusikaye erina riwe, tumuhe mitima yetu, tukandisyahika wuwe, hate n'obuige.",
"116. NGAHA EBIOSI KU YESU":"MARY D. JAMES\n\n1. Ebiala biage ni biwe, Ebiangamukolera, N'ebisandu biage nabio, biangamukwamirira. Ebiosi biosi ku Yesu, nangamukwanirirara.\n\n2. Ameso wage ku Yesu, Nobunora, sinyisamalire 'gundi, nina Yesu Mukama. Yesu, Yesu iyowene, Oyo wakwa komutiti.\n\n3. NamaSwe ka, namnasWeka, bosana nOmukama, Yesu Muami muenge wetu, Anzire mundu ngangye.\nTumupipe, tumupipe, anzire 'mundu ngangyengye.",
"117. KWAMA, KWAMA, WANGAKWAMA YESU":"1. Kwama, kwama, wangakwama Yesu, ka akuholera oko Kalvari, kwama, kwama, wangakwama Yesu, Angaminya oluanzo luawe ati?\n\n2. Kwama, kwama, wangakwama Yesu, hakuhi, nehali, wangamukwama, kwama, kwama, wangakwama Yesu, Siwangibirirwa kiakukolera.",
"118. NGANDIBAYIRA BASOHI":"HARRY D. CLARKE/ HARRY D. CLARKE Har. by TALMAGE J. BITTIKOFER\n\n1. Ngandibayira basohi, abasohi, abasohi, Mukandisyasoha bandu, muamanyikwama, muamanyikwama, muamanyikwama, ngandibayira'basohi, muamanyikwama.\n\n2. Kristo akabirikira, muase kuingye, muase kuingye, Kristo abiritulaga, eriluhuka. Eriluhuka, Eriluhuka, Krtsto abiritulaga, eriluhuka.\n\n3. Tuangambala emipira, emipira, eyoMungu, Tuangabya bafundi buwe, tuamamukwama. Tuambale Yesu, Tuambale Yesu, asyatuyira'basohi, tuamamukwama.",
"119. YESU AMABIRIKIRA":"Mrs. CECIL F. ALEXANDER/ WILLIAM H. JUDE\n\n1. Yesu amabirikira tuleke nzira nyibi, Tumu kwame, tumupipe, tumuanze, ni Mulamia.\n\n2. Omusasi wOMulamia akeraya ebibi, Abiritugula mugo, tuangamuha wasingya.\n\n3. Omukama Yesu Kristo akandiSyasa kandi, Neri henia erioMungu, n'abalaika abosi.",
"120. OMUSASI ANGERIA EBIBI":"EL NATHAN/ JAMES MC GRANAHAN\n\n1. Omusasi 0gutika a ngeria ebibi, Nimusasi Womulamia yo wagalawa.\n\nNi kitabu, ekioMungu, kikatubwirago,\n(ni kitabu, ekioMungu,)\nOmusasi, wOmulania, angeria ebibi.\n(OnusaSi, wOmulamia,)\n\n2. Erilamia eria Yesu, kahabawa rio, Oko Muti waKalvari moaheka ebibi.\n\n3. Erihitana rioMungu eriendibya kui twe, Moriahirwa oko Yesu, moa turihirario.",
"121. EBIBI BINGI BIAMAKULUHLA":"G H. M./ C. H. MORRIS\n\n1. Ebibi bingi biamaku luhia, wase koYesu lino lino, naye aka ndilu Syabio biosi, Uwe, hike koYesu.\n\nLino, wangowa Yesu, subye ukagana Ye, ubindule mutima, uhike ku Yesu linno.\n\n2. Uamasonda mutima wene, uikiriraye Yesu lino, ulangire lu si luengebe, Uhike koYesu lino.\n\n3. Bulige bya mabya bui bungi, uikiriraye Yesu lino, Setani siiri neritsema, Uwe, hike koYesu.\n\n4. BaKristo ba kakubirikira, uikiriraye Yesu lino, nawe iwikala nobutseme, Uhike ku Yesu lino.",
      
};


function populateHymnSelector() {
    const hymnSelector = document.getElementById("hymnSelector");
    Object.keys(hymnsData).forEach(hymn => {
        const option = document.createElement("option");
        option.value = hymn;
        option.textContent = hymn;
        hymnSelector.appendChild(option);
    });
}

const urlParams = new URLSearchParams(window.location.search);
const currentTitle = urlParams.get('title');

function getAdjacentHymn(direction) {
    const titles = Object.keys(hymnsData);
    const currentIndex = titles.indexOf(currentTitle);

    if (direction === 'next' && currentIndex < titles.length - 1) {
        return titles[currentIndex + 1];
    } else if (direction === 'previous' && currentIndex > 0) {
        return titles[currentIndex - 1];
    }
    return null;
}

let touchStartX = 0;
let touchEndX = 0;

document.addEventListener('touchstart', (e) => {
    touchStartX = e.touches[0].clientX;
});

document.addEventListener('touchend', (e) => {
    touchEndX = e.changedTouches[0].clientX;
    handleSwipe();
});

function handleSwipe() {
    const swipeDistance = touchStartX - touchEndX;
    if (swipeDistance > 150) {
        const nextHymn = getAdjacentHymn('next');
        if (nextHymn) {
            window.location.href = `NAPp.html?title=${encodeURIComponent(nextHymn)}`;
        }
    } else if (swipeDistance < -150) {
        const previousHymn = getAdjacentHymn('previous');
        if (previousHymn) {
            window.location.href = `NAPp.html?title=${encodeURIComponent(previousHymn)}`;
        }
    }
}

document.querySelectorAll('.hymn').forEach(button => {
    button.addEventListener('click', () => {
        const hymnTitle = button.getAttribute('data-title');
        window.location.href = `NAPp.html?title=${encodeURIComponent(hymnTitle)}`;
    });
});

function performSearch() {
    const searchTerm = document.getElementById('song-search').value.toLowerCase();
    const matchedHymns = Object.keys(hymnsData).filter(title => 
        title.toLowerCase().includes(searchTerm) || 
        hymnsData[title].toLowerCase().includes(searchTerm)
    );

    const lyricsDiv = document.getElementById('lyrics');

    if (matchedHymns.length > 0) {
        const hymnList = matchedHymns.map(hymn => `<button class="hymn" data-title="${hymn}">${hymn}</button>`).join('');
        lyricsDiv.innerHTML = `<h5>Nyimbo zinazolingana:</h5><div class="hymn-button">${hymnList}</div>`;
        lyricsDiv.hidden = false;

        matchedHymns.forEach(hymn => {
            const button = document.querySelector(`.hymn[data-title="${hymn}"]`);
            button.addEventListener('click', () => {
                window.location.href = `NAPp.html?title=${encodeURIComponent(hymn)}`;
            });
        });
    } else {
        lyricsDiv.innerText = 'Hakuna nyimbo inayolingana iliyopatikana.';
        lyricsDiv.hidden = false;
    }
}

document.getElementById('search-button').addEventListener('click', performSearch);

document.getElementById('song-search').addEventListener('keyup', (e) => {
    if (e.key === 'Enter') {
        performSearch();
    } else {
        performSearch();
    }
});

function changeTheme() {
    const themeBtn = document.getElementById('theme');
    themeBtn.innerHTML = themeBtn.innerHTML === '🌙' ? '☀' : '🌙';
}


let startX = null;

function setupSwipeNavigation() {
    const lyricsContainer = document.getElementById('hlyrics');
    lyricsContainer.addEventListener('touchstart', handleTouchStart, false);
    lyricsContainer.addEventListener('touchmove', handleTouchMove, false);
}

function handleTouchStart(event) {
    startX = event.touches[0].clientX;
}

function handleTouchMove(event) {
    if (!startX) return;

    const endX = event.touches[0].clientX;
    const difference = startX - endX;

    if (Math.abs(difference) > 30) {
        if (difference > 0) {
            goToNextHymn();
        } else {
            goToPreviousHymn();
        }
        startX = null;
    }
}

function goToNextHymn() {
    const currentIndex = Object.keys(hymnsData).indexOf(currentTitle);
    const nextIndex = (currentIndex + 1) % Object.keys(hymnsData).length;
    const nextTitle = Object.keys(hymnsData)[nextIndex];
    window.location.href = `NAPp.html?title=${encodeURIComponent(nextTitle)}`;
}

function goToPreviousHymn() {
    const currentIndex = Object.keys(hymnsData).indexOf(currentTitle);
    const previousIndex = (currentIndex - 1 + Object.keys(hymnsData).length) % Object.keys(hymnsData).length;
    const previousTitle = Object.keys(hymnsData)[previousIndex];
    window.location.href = `NAPp.html?title=${encodeURIComponent(previousTitle)}`;
}

document.getElementById('back').addEventListener('click', () => {
    window.history.back();
});

